# Generated by Django 4.0.5 on 2022-06-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('rank', models.FloatField()),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=15)),
                ('supply', models.FloatField()),
                ('marketCapUsd', models.FloatField()),
                ('volumeUsd24Hr', models.FloatField()),
                ('priceUsd', models.FloatField()),
                ('changePercent24Hr', models.FloatField()),
                ('vwap24Hr', models.FloatField()),
            ],
        ),
    ]
