# Generated by Django 4.0.5 on 2022-06-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqttviz_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='rank',
            field=models.PositiveIntegerField(),
        ),
    ]
